Dcron/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scheduled_tasks.urls.views_urls', namespace='scheduled_tasks'))
]

api_urlpatterns = [
    path('api/v1/scheduled_tasks/', include('scheduled_tasks.urls.api_urls', namespace='api-scheduled_tasks'))
]

urlpatterns += api_urlpatterns
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

scheduled_tasks/models.py
# encoding: utf-8
from __future__ import unicode_literals

from django.db import models

"""
class ScheduledTask(models.Model):

    class META:
        db_table = 'scheduledTask'
"""

scheduled_tasks/forms/scheduled_tasks.py
from Dcron.celery import app

from django import forms
from django.utils.translation import ugettext_lazy as _
from django_celery_beat.admin import PeriodicTaskForm, TaskChoiceField
from django_celery_beat.models import PeriodicTask


class ScheduledTasksForm(PeriodicTaskForm):

    task = forms.CharField(
        label=_('Task (custom)'),
        required=False,
        max_length=200,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'task name', 'readonly': 'readonly'})
    )

    class Meta:
        """Form metadata."""

        model = PeriodicTask
        fields = [
            'name', 'task', 'regtask', 'enabled', 'description', 'interval', 'crontab', 'solar', 'start_time', 'one_off', 'args', 'kwargs'
        ]

        help_texts = {
            'start_time': 'Please follow example time format. 2019-09-20 15:00:00'
        }

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control', 'placeholder': 'Scheduled Task Name'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control', 'placeholder': 'Description'
            }),
            'args': forms.Textarea(attrs={
                'class': 'form-control', 'placeholder': 'Description'
            }),
            'kwargs': forms.Textarea(attrs={
                'class': 'form-control', 'placeholder': 'Description'
            }),
            'interval': forms.Select(attrs={
                'class': 'form-control', 'placeholder': 'Interval'
            }),
            'crontab': forms.Select(attrs={
                'class': 'form-control', 'placeholder': 'crontab'
            }),
            'solar': forms.Select(attrs={
                'class': 'form-control', 'placeholder': 'solar'
            }),
            'start_time': forms.DateTimeInput(attrs={
                'class': 'form-control', 'placeholder': 'start_time'
            }),
        }

scheduled_tasks/views/index.py
from django.views.generic import TemplateView
from django_celery_beat.models import PeriodicTask


class DemoView(TemplateView):
    template_name = 'demo.html'

    def get_context_data(self, **kwargs):
        context = {
            'scheduled_tasks': PeriodicTask.objects.all()
        }
        kwargs.update(context)
        return super(DemoView, self).get_context_data(**kwargs)


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = {
            'scheduled_tasks': PeriodicTask.objects.all()
        }
        kwargs.update(context)
        return super(IndexView, self).get_context_data(**kwargs)

scheduled_tasks/views/scheduled_tasks.py
from django.views.generic import TemplateView, UpdateView, ListView
from django.urls import reverse_lazy
from django_celery_beat.models import PeriodicTask

from scheduled_tasks.forms import ScheduledTasksForm
from scheduled_tasks.utils import action_handler


class ScheduledTasksView(ListView):
    template_name = 'scheduled_tasks/list.html'
    queryset = PeriodicTask.objects.all()
    context_object_name = 'scheduled_tasks'

    def get_context_data(self, **kwargs):
        context = {
            # 'scheduled_tasks': PeriodicTask.objects.all()
            'error': kwargs.get('error', None),
        }
        kwargs.update(context)
        return super(ScheduledTasksView, self).get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        return super(ScheduledTasksView, self).get(request, *args, **kwargs)

    def post(self, request, **kwargs):
        # print(self.request.POST)
        action = self.request.POST.get('action')
        select_list = [int(tid) for tid in self.request.POST.getlist('_select_action')]
        self.object_list = self.get_queryset()
        if not action or not select_list:
            return self.render_to_response(self.get_context_data(error='no args found'))

        # print(action)
        # print(select_list)
        action_handler(action=action, select_list=select_list)
        return self.render_to_response(self.get_context_data())


class ScheduledTasksUpdateView(UpdateView):
    template_name = 'scheduled_tasks/update.html'
    form_class = ScheduledTasksForm
    model = PeriodicTask
    success_url = reverse_lazy('scheduled_tasks:scheduled_tasks')

scheduled_tasks/templates/scheduled_tasks/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DCron</title>
</head>
<body>
    <p>定时任务管理系统</p>
</body>
</html>

scheduled_tasks/templates/scheduled_tasks/list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card tasks">
                <div class="card-header">
                    <h4>Scheduled Tasks</h4>
                    <!--<div class="card-header-right-icon">
                        <ul>
                            <li class="card-close" data-dismiss="alert"><i class="ti-close"></i></li>
                        </ul>
                    </div>-->
                    {% if error %}
                        <div class="alert alert-warning alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                            <strong>Error!</strong> {{ error }}
                        </div>
                    {% endif %}
                    <div style="float: right;">
                        <!--<label for="id_search">search</label>
                        <input type="text" id="id_search">-->
                        <button type="button" class="btn btn-info btn-add"><i class="ti-plus"></i>Add new scheduled task</button>
                    </div>

                </div>
                <form class="action-form" method="post">
                {% csrf_token %}
                    <div class="actions">
                        <div class="form-group col-sm-2">
                            <label for="id_action">Action:</label>
                            <select class="" name="action" id="id_action">
                                <option value="">------</option>
                                <option value="delete">delete</option>
                                <option value="enable">enable</option>
                                <option value="disable">disable</option>
                                <option value="run">run</option>
                            </select>
                        </div>
                        <button class="btn btn-action" type="submit">go</button>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <td>定时任务</td>
                                <td>任务名称</td>
                                <td>任务状态</td>
                                <td>上次执行时间</td>
                                <td>操作</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                        {% for task in scheduled_tasks %}
                            <tr>
                                {% if task.interval %}
                                    <td><a href="{% url 'scheduled_tasks:scheduled_tasks_update' pk=task.id %}">{{ task.name }}:{{ task.interval }}</a></td>
                                {% elif task.crontab %}
                                <td><a href="{% url 'scheduled_tasks:scheduled_tasks_update' pk=task.id %}">{{ task.name }}:{{ task.crontab }}</a></td>
                                {% elif task.solar %}
                                <td><a href="{% url 'scheduled_tasks:scheduled_tasks_update' pk=task.id %}">{{ task.name }}:{{ task.solar }}</a></td>
                                {% endif %}
                                <td>{{ task.task }}</td>
                                {% if task.enabled %}
                                    <td><i class="ti-check"></i></td>
                                {% else %}
                                    <td><i class="ti-close"></i></td>
                                {% endif %}
                                <td>{{ task.last_run_at }}</td>
                                <td>
                                    <button class="btn btn-primary">功能1</button>
                                    <button class="btn btn-primary">功能2</button>
                                </td>
                                <td class="action-checkbox">
                                    <input class="action-select" type="checkbox" name="_select_action" value="{{ task.id }}">
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

scheduled_tasks/templates/scheduled_tasks/update.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card tasks">
                <div class="card-header">
                    <h4>Scheduled Tasks Update</h4>
                </div>

                <div class="card-body">
                <h4>Basic</h4>
                    <div class="horizontal-form-elements">
                        <form class="form-horizontal" method="post">
                            {% if form.errors %}
                                 <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                     <strong>{{ form.errors }}</strong>
                                 </div>
                            {% endif %}
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-9">
                                    <div class="form-group">
                                        <label for="id_name" class="col-sm-2 control-label">Name:</label>
                                        <div class="col-sm-7">
                                            {{ form.name }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_task" class="col-sm-2 control-label">Task (custom):</label>
                                        <div class="col-sm-7">
                                            {{ form.task }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_regtask" class="col-sm-2 control-label">Task (registered):</label>
                                        <div class="col-sm-7">
                                            {{ form.regtask }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_enabled" class="col-sm-2 control-label">
                                            Enabled:</label>
                                        <div class="col-sm-7">
                                            {{ form.enabled }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_description" class="col-sm-2 control-label">Description:</label>
                                        <div class="col-sm-7">
                                            {{ form.description }}
                                        </div>
                                    </div>
                                    <h4>Schedule</h4>
                                    <div class="form-group">
                                        <label for="id_interval" class="col-sm-2 control-label">Interval:</label>
                                        <div class="col-sm-7">
                                            {{ form.interval }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_crontab" class="col-sm-2 control-label">Crontab:</label>
                                        <div class="col-sm-7">
                                            {{ form.crontab }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_solar" class="col-sm-2 control-label">Solar:</label>
                                        <div class="col-sm-7">
                                            {{ form.solar }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_start_time" class="col-sm-2 control-label">Start_time:</label>
                                        <div class="col-sm-7">
                                            {{ form.start_time }}
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_enabled" class="col-sm-2 control-label">
                                            One off task:</label>
                                        <div class="col-sm-7">
                                            {{ form.one_off }}
                                        </div>
                                    </div>
                                    <div class="col-lg-9">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse4" aria-expanded="true" class="">Arguments</a></h4>
                                            </div>
                                            <div id="collapse4" class="panel-collapse collapse">
                                                <div class="form-group">
                                                    <label for="id_args" class="col-sm-2 control-label">Arguments:</label>
                                                        <div class="col-sm-7">
                                                            {{ form.args }}
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label for="id_kwargs" class="col-sm-2 control-label">Keyword arguments:</label>
                                                        <div class="col-sm-7">
                                                            {{ form.kwargs }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button class="btn btn-success" type="submit">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footjs %}
    <script>
        jQuery(document).ready(function () {
            $('#id_regtask').attr('class', 'form-control');
        })
    </script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Home</title>

	<!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

	<!-- Styles -->
    <!-- <link href="/data/static/assets/css/lib/font-awesome.min.css" rel="stylesheet">-->
    <link href="{% static 'assets/css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <!-- <link href="assets/css/lib/themify-icons.css" rel="stylesheet">-->
    <link href="{% static 'assets/css/lib/themify-icons.css' %}" rel="stylesheet">
    <!-- <link href="assets/css/lib/owl.carousel.min.css" rel="stylesheet" />-->
    <link href="{% static 'assets/css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <!-- <link href="assets/css/lib/owl.theme.default.min.css" rel="stylesheet" />-->
    <link href="{% static 'assets/css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <!-- <link href="assets/css/lib/weather-icons.css" rel="stylesheet" />-->
    <link href="{% static 'assets/css/lib/weather-icons.css' %}" rel="stylesheet" />
    <!-- <link href="assets/css/lib/mmc-chat.css" rel="stylesheet" />-->
    <link href="{% static 'assets/css/lib/mmc-chat.css' %}" rel="stylesheet" />
    <!-- <link href="assets/css/lib/sidebar.css" rel="stylesheet">-->
    <link href="{% static 'assets/css/lib/sidebar.css' %}" rel="stylesheet" />
    <!-- <link href="assets/css/lib/bootstrap.min.css" rel="stylesheet">-->
    <link href="{% static 'assets/css/lib/bootstrap.min.css' %}" rel="stylesheet" />
    <!-- <link href="assets/css/lib/simdahs.css" rel="stylesheet">-->
    <link href="{% static 'assets/css/lib/simdahs.css' %}" rel="stylesheet" />
    <!-- <link href="assets/css/style.css" rel="stylesheet">-->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    {% block headcss %}
    {% endblock %}


</head>

<body>

    {% include 'sidebar.html' %}
    {% include 'header.html' %}
    {% include 'chat_sidebar.html' %}
    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                {% block page_head %}
                {% include 'page_head.html' %}
                {% endblock %}
                <div class="main-content">
                    {% block content %}
                    {% endblock %}
                </div>
     <!-- /# main content -->Copyright &copy; 2019.Company name All rights reserved.<a target="_blank" href="#"></a>
            </div><!-- /# container-fluid -->
        </div><!-- /# main -->
    </div><!-- /# content wrap -->



    <script src="{% static 'assets/js/lib/jquery.min.js' %}"></script><!-- jquery vendor -->
    <script src="{% static 'assets/js/lib/jquery.nanoscroller.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/sidebar.js' %}"></script>
    <script src="{% static 'assets/js/lib/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/mmc-common.js' %}"></script>
    <script src="{% static 'assets/js/lib/mmc-chat.js' %}"></script>

	<!--  Chart js -->
	<script src="{% static 'assets/js/lib/chart-js/Chart.bundle.js' %}"></script>
    <script src="{% static 'assets/js/lib/chart-js/chartjs-init.js' %}"></script>

	<!-- // Chart js -->
    <script src="{% static 'assets/js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
	<script src="{% static 'assets/js/lib/sparklinechart/sparkline.init.js' %}"></script>

	<!--  Datamap -->
    <script src="{% static 'assets/js/lib/datamap/d3.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/datamap/topojson.js' %}"></script>
    <script src="{% static 'assets/js/lib/datamap/datamaps.world.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/datamap/datamap-init.js' %}"></script>
	<!-- // Datamap -->-->
    <script src="{% static 'assets/js/lib/weather/jquery.simpleWeather.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/weather/weather-init.js' %}"></script>
    <script src="{% static 'assets/js/lib/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
</body>
    {% block footjs %}
    {% endblock %}
</html>

templates/chat_sidebar.html
{% load static %}
	<div class="chat-sidebar">
        <!-- BEGIN chat -->
        <div id="mmc-chat" class="color-default">
            <!-- BEGIN CHAT BOX -->
            <div class="chat-box">
                <!-- BEGIN CHAT BOXS -->
                <ul class="boxs"></ul>
                <!-- END CHAT BOXS -->
                <div class="icons-set">
                    <div class="stickers">
                        <div class="had-container">
                            <div class="row">
                                <div class="s12">
                                    <ul class="tabs" style="width: 100%;height: 60px;">
                                        <li class="tab col s3">
                                            <a href="#tab1" class="active">
                                                <img src="{% static 'assets/images/1.png' %}" alt="" />
                                            </a>
                                        </li>
                                        <li class="tab col s3"><a href="#tab2">Test 2</a></li>
                                    </ul>
                                </div>
                                <div id="tab1" class="s12 tab-content">
                                    <ul>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                        <li><img src="{% static 'assets/images/1.png' %}" alt="" /></li>
                                    </ul>
                                </div>
                                <div id="tab2" class="s12 tab-content">Test 2</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END CHAT BOX -->
            <!-- BEGIN SIDEBAR -->
            <div id="sidebar" class="right scroll">
                <div class="had-container">
                    <!-- BEGIN USERS -->
                    <div class="users">

                        <ul class="user-list">
                            <!-- BEGIN USER-->
                            <li class="user-tooltip" data-id="1" data-status="online" data-username="Rufat Askerov" data-position="left" data-filter-item data-filter-name="rufat askerov">
                                <!-- BEGIN USER IMAGE-->
                                <div class="user-image">
                                    <img src="{% static 'assets/images/avatar/1.jpg' %}" class="avatar" alt="Rufat Askerov" />
                                </div>
                                <!-- END USER IMAGE-->
                                <!-- BEGIN USERNAME-->
                                <span class="user-name">Rufat Askerov</span>
								<span class="user-show"></span>
                                <!-- END USERNAME-->
                            </li>
                            <!-- END USER-->
                            <!-- BEGIN USER-->
                            <li class="user-tooltip" data-id="3" data-status="online" data-username="Alice" data-position="left" data-filter-item data-filter-name="alice">
                                <div class="user-image">
                                    <img src="{% static 'assets/images/avatar/1.jpg' %}" class="avatar" alt="Alice" />
                                </div>
                                <span class="user-name">Alice</span>
								<span class="user-show"></span>
                            </li>

                            <!-- BEGIN USER-->
                            <li class="user-tooltip" data-id="7" data-status="offline" data-username="Michael Scofield" data-position="left" data-filter-item data-filter-name="michael scofield">
                                <div class="user-image">
                                    <img src="{% static 'assets/images/avatar/1.jpg' %}" class="avatar" alt="Michael Scofield" />
                                </div>
                                <span class="user-name">Michael Scofield</span>
								<span class="user-show"></span>
                            </li>

                            <!-- BEGIN USER-->
                            <li class="user-tooltip" data-id="5" data-status="online" data-username="Irina Shayk" data-position="left" data-filter-item data-filter-name="irina shayk">
                                <div class="user-image">
                                    <img src="{% static 'assets/images/avatar/1.jpg' %}" class="avatar" alt="Irina Shayk" />
                                </div>
                                <span class="user-name">Irina Shayk</span>
								<span class="user-show"></span>
                            </li>

                            <!-- BEGIN USER-->
                            <li class="user-tooltip" data-id="6" data-status="offline" data-username="Sara Tancredi" data-position="left" data-filter-item data-filter-name="sara tancredi">
                                <div class="user-image">
                                    <img src="{% static 'assets/images/avatar/1.jpg' %}" class="avatar" alt="Sara Tancredi" />
                                </div>
                                <span class="user-name">Sara Tancredi</span>
								<span class="user-show"></span>
                            </li>

                            <!-- BEGIN USER-->
                            <li class="user-tooltip" data-id="7" data-status="offline" data-username="Wolf" data-position="left" data-filter-item data-filter-name="Wolf">
                                <div class="user-image">
                                    <img src="{% static 'assets/images/avatar/1.jpg' %}" class="avatar" alt="Wolf" />
                                </div>
                                <span class="user-name">Wolf</span>
								<span class="user-show"></span>
                            </li>
                        </ul>
						<div class="chat-user-search">
							<div class="input-group">
								<span class="input-group-addon"><i class="ti-search"></i></span>
								<input type="text" class="form-control" placeholder="Search"  data-search />
							</div>
						</div>
                    </div>
                    <!-- END USERS -->

                </div>
            </div>
            <!-- END SIDEBAR -->
        </div>
        <!-- END chat -->
    </div>
    <!-- END chat Sidebar-->

templates/index.html
{% extends 'base.html' %}

templates/page_head.html
<div class="row">
    <div class="col-lg-8 p-0">
        <div class="page-header">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div><!-- /# column -->
    <div class="col-lg-4 p-0">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Dashboard</a></li>
                    <li class="active">Home</li>
                </ol>
            </div>
        </div>
    </div><!-- /# column -->
</div><!-- /# row -->